(function(){
'use strict'

const icons={
 archive:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18M9 13h6M5 2h14"/>',building:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M9 21v-4h6v4M8 7h.01M12 7h.01M16 7h.01M8 11h.01M12 11h.01M16 11h.01"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',chart:'<path d="M3 3v18h18M7 16l4-5 4 3 5-7"/>','chevron-down':'<path d="m6 9 6 6 6-6"/>','chevron-right':'<path d="m9 18 6-6-6-6"/>',clipboard:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4.5V3h6v1.5M9 9h6M9 13h6M9 17h4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.66 3.58 3 8 3s8-1.34 8-3V5M4 11v6c0 1.66 3.58 3 8 3s8-1.34 8-3v-6"/>',download:'<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>','file-chart':'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 18v-3M12 18v-6M16 18v-8"/>',flask:'<path d="M9 3h6M10 9V3h4v6l5 9a2 2 0 0 1-1.74 3H6.74A2 2 0 0 1 5 18Z"/><path d="M7.5 15h9"/>',gauge:'<path d="M20.38 8.57a9 9 0 1 0 .13 6.58"/><path d="m12 12 4-4"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',maximize:'<path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/>',moon:'<path d="M20.5 14.5A8.5 8.5 0 0 1 9.5 3.5 9 9 0 1 0 20.5 14.5Z"/>','panel-left':'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M14 9l-3 3 3 3"/>',receipt:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2Z"/><path d="M9 8h6M9 12h6M9 16h4"/>',refresh:'<path d="M20 7h-5V2M4 17h5v5"/><path d="M5.2 9A8 8 0 0 1 18 5l2 2M18.8 15A8 8 0 0 1 6 19l-2-2"/>',scan:'<path d="M3 7V5a2 2 0 0 1 2-2h2M17 3h2a2 2 0 0 1 2 2v2M21 17v2a2 2 0 0 1-2 2h-2M7 21H5a2 2 0 0 1-2-2v-2M7 12h10"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',store:'<path d="M3 9l2-6h14l2 6M5 13v8h14v-8M9 21v-6h6v6"/><path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"/>','triangle-alert':'<path d="m21.7 18-8-14a2 2 0 0 0-3.4 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3Z"/><path d="M12 9v4M12 17h.01"/>',wrench:'<path d="M14.7 6.3a4 4 0 0 0-5-5L12 3.6 9.6 6 7.3 3.7a4 4 0 0 0 5 5L4 17a2 2 0 1 0 3 3l7.7-8.3a4 4 0 0 0 0-5.4Z"/>',x:'<path d="M18 6 6 18M6 6l12 12"/>'
}
const svgIcon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||''}</svg>`
const $=id=>document.getElementById(id)
const page=document.documentElement.dataset.analyticsV2Page
const fmt=value=>new Intl.NumberFormat('zh-CN').format(Math.round(value))
const rate=(part,total)=>total?part/total*100:0
const average=(total,count)=>count?total/count:0
const pct=value=>`${value.toFixed(2)}%`
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value))
const css=name=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()
let toastTimer,drawerContext='',qualityRankMetric='timely',attentionType='station',reportDimension='date',reportStateIndex=0

document.querySelectorAll('[data-icon]').forEach(node=>{if(icons[node.dataset.icon])node.innerHTML=svgIcon(node.dataset.icon)})

const qualitySets={
 region:[
  ['华东大区','REG-EAST',1862,1830,1763,1351,6377.2,11],['华南大区','REG-SOUTH',1241,1211,1146,858,4029.1,15],['华北大区','REG-NORTH',1096,1057,1009,721,3362.3,13],['华中大区','REG-CENTRAL',892,857,827,620,2915.8,7],['西南大区','REG-SOUTHWEST',768,729,701,505,2363.4,8],['西北大区','REG-NORTHWEST',623,578,541,394,1830.4,6],['东北大区','REG-NORTHEAST',582,537,508,368,1746.6,3]
 ],
 station:[
  ['上海浦东服务站','SH-PD-001',268,247,237,192,879.4,6],['北京朝阳服务站','BJ-CY-002',231,216,206,162,754.9,4],['广州天河服务站','GZ-TH-003',208,196,188,151,711.2,3],['成都高新服务站','CD-GX-004',187,178,170,137,656.2,2],['西安未央服务站','XA-WY-005',162,148,142,111,501.7,4],['杭州拱墅服务站','HZ-GS-006',154,149,143,108,517.3,1],['武汉江汉服务站','WH-JH-007',146,139,132,98,463.8,2]
 ],
 personnel:[
  ['李二雷','SP-0002',73,70,68,51,243.8,1],['孙志远','SP-0005',69,66,62,46,217.1,1],['陈海峰','SP-0011',65,61,59,45,213.4,0],['王建国','SP-0017',61,57,55,42,196.5,2],['赵明宇','SP-0023',58,55,51,39,182.1,1],['周立新','SP-0032',54,50,49,36,169.9,1],['黄嘉伟','SP-0041',51,47,45,33,154.4,2]
 ]
}
function qualityRows(type){return qualitySets[type].map((item,index)=>({id:`${type}-${index+1}`,name:item[0],code:item[1],serviceCount:item[2],onTimeCount:item[3],firstTimeResolvedCount:item[4],ratedCount:item[5],ratingTotal:item[6],complaintCount:item[7],timely:rate(item[3],item[2]),firstFix:rate(item[4],item[2]),rating:average(item[6],item[5]),ratingCoverage:rate(item[5],item[2]),complaintRate:rate(item[7],item[2])}))}
const qualitySummary={serviceCount:7642,onTimeCount:7344,firstTimeResolvedCount:7076,ratedCount:5217,ratingTotal:24624.24,complaintCount:63}
const qualityTrend=Array.from({length:30},(_,index)=>{
 const wave=[-18,-8,6,14,2,-12,9,21,4,-7,17,28,12,5,-11,19,32,18,3,-14,8,25,16,-2,-15,4,23,12,30,17][index]
 const serviceCount=238+wave
 const timely=95.1+[0,.4,.7,.1,.3,.8,.5,.2,.9,.4,.6,1.1,.5,.2,.8,.4,.7,.9,.3,.1,.5,.8,.4,.6,.2,.7,.9,.5,1.0,1.2][index]
 const firstFix=91.4+[.2,.5,.1,.6,.4,.9,.3,.7,.5,.2,.8,1.0,.4,.6,.1,.5,.9,.7,.3,.4,.8,.6,.2,.5,.1,.7,.9,.4,.8,1.1][index]
 const date=new Date(2026,7,22+index)
 return {date:`${String(date.getMonth()+1).padStart(2,'0')}/${String(date.getDate()).padStart(2,'0')}`,serviceCount,timely,firstFix}
})

const reportGroups={
 date:[['09/16',221,176,8,9],['09/15',208,162,7,6],['09/07',204,158,6,6],['09/19',203,159,9,4],['09/12',198,150,8,5],['09/05',195,151,5,4],['09/03',191,149,7,3]],
 type:[['安装',1774,1392,48,31],['维修',1569,1198,54,43],['指导',392,314,14,8]],
 source:[['消费者',1531,1176,45,39],['门店',1195,947,37,21],['客服',1009,781,34,22]],
 province:[['江苏省',624,488,18,15],['浙江省',587,461,15,13],['广东省',541,414,21,17],['上海市',496,392,10,9],['北京市',421,326,13,11],['四川省',362,279,16,10],['湖北省',304,236,11,7]],
 station:[['上海浦东服务站',268,211,8,6],['北京朝阳服务站',231,179,7,4],['广州天河服务站',208,160,9,3],['成都高新服务站',187,146,8,2],['西安未央服务站',162,123,7,4],['杭州拱墅服务站',154,122,4,1],['武汉江汉服务站',146,114,5,2]],
 store:[['上海旗舰店',312,244,9,7],['杭州城西门店',286,226,7,5],['广州天河门店',254,194,11,8],['北京朝阳门店',241,188,6,4],['成都高新门店',219,168,10,6],['南京河西门店',196,153,5,3],['武汉江汉门店',174,136,6,4]],
 product:[['智能坐便器 G5',487,371,16,12],['卫洗丽 TCF8',452,356,12,9],['智能坐便器 G3',419,329,15,10],['台盆龙头 TLS',386,306,9,7],['浴缸 PAY',347,271,13,8],['淋浴花洒 TBW',328,258,11,6],['普通坐便器 CW',301,238,8,5]]
}
const reportLabels={date:'日期',type:'服务类型',source:'建单来源',province:'服务省份',station:'服务站',store:'门店',product:'商品'}
const reportSummary={orderCount:3735,closedCount:2904,cancelledCount:116,complaintOrderCount:82}
const reportTrend=qualityTrend.map((item,index)=>({date:item.date,orderCount:Math.round(item.serviceCount*.82),closedCount:Math.round(item.serviceCount*.64),cancelledCount:3+(index%6),complaintOrderCount:2+(index%5)}))

function showToast(message){const toast=$('toast');toast.textContent=message;toast.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2600)}
function updateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(node=>{if(icons[node.dataset.icon])node.innerHTML=svgIcon(node.dataset.icon)})}
function openDrawer(title,html,context){drawerContext=context;$('drawerTitle').textContent=title;$('drawerContent').innerHTML=html;$('scrim').hidden=false;$('analyticsDrawer').hidden=false;updateIcons($('analyticsDrawer'))}
function closeDrawer(){$('scrim').hidden=true;$('analyticsDrawer').hidden=true}
function detailHtml(items,note){return `<div class="detail-hero"><span>当前对象</span><strong>${items[0][1]}</strong></div><div class="detail-grid">${items.slice(1).map(item=>`<div class="detail-field"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join('')}</div><div class="drawer-note">${note}</div>`}
function setValidation(id,message){const node=$(id);node.textContent=message;node.hidden=!message}
function setUpdated(){$('lastUpdated').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}
function pulse(){const workspace=$('workspace');workspace.classList.add('is-refreshing');setTimeout(()=>workspace.classList.remove('is-refreshing'),620)}

function setupCanvas(canvas,draw){const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const context=canvas.getContext('2d');context.setTransform(dpr,0,0,dpr,0,0);draw(context,rect.width,rect.height)}
function chartColors(){return {text:css('--text-3')||'#65738a',grid:css('--border')||'#e4e9f0',primary:css('--primary')||'#3b78e7',primarySoft:'rgba(60,126,236,.18)',teal:'#12a7a2',amber:css('--amber')||'#e8a03a',danger:css('--danger')||'#dc5060',surface:css('--surface')||'#fff'}}
function drawLine(context,points,color,width=2){context.beginPath();points.forEach((point,index)=>index?context.lineTo(point.x,point.y):context.moveTo(point.x,point.y));context.strokeStyle=color;context.lineWidth=width;context.lineJoin='round';context.lineCap='round';context.stroke();points.forEach(point=>{context.beginPath();context.arc(point.x,point.y,2.4,0,Math.PI*2);context.fillStyle=color;context.fill();context.beginPath();context.arc(point.x,point.y,1.1,0,Math.PI*2);context.fillStyle=chartColors().surface;context.fill()})}
function drawQualityTrend(){const canvas=$('qualityTrendCanvas');if(!canvas)return;setupCanvas(canvas,(context,width,height)=>{const color=chartColors(),plot={x:38,y:12,w:width-72,h:height-42},maxVolume=Math.max(...qualityTrend.map(item=>item.serviceCount))*1.12;context.font='9px system-ui';context.fillStyle=color.text;context.textAlign='right';for(let index=0;index<5;index+=1){const y=plot.y+plot.h/4*index;context.strokeStyle=color.grid;context.lineWidth=1;context.beginPath();context.moveTo(plot.x,y);context.lineTo(plot.x+plot.w,y);context.stroke();context.fillText(`${Math.round(maxVolume*(4-index)/4)}`,plot.x-7,y+3)}const timely=[],firstFix=[],hit=[];qualityTrend.forEach((item,index)=>{const step=plot.w/qualityTrend.length,x=plot.x+index*step+step*.5,barH=item.serviceCount/maxVolume*plot.h;context.fillStyle=color.primarySoft;context.fillRect(x-step*.29,plot.y+plot.h-barH,step*.58,barH);const ty=plot.y+plot.h-(item.timely-88)/12*plot.h,fy=plot.y+plot.h-(item.firstFix-88)/12*plot.h;timely.push({x,y:ty});firstFix.push({x,y:fy});hit.push({x,item});if(index%5===0||index===qualityTrend.length-1){context.fillStyle=color.text;context.textAlign='center';context.fillText(item.date,x,height-8)}});drawLine(context,timely,color.primary,2);drawLine(context,firstFix,color.teal,2);canvas._chartPoints=hit})}
function drawReportTrend(){const canvas=$('reportTrendCanvas');if(!canvas)return;setupCanvas(canvas,(context,width,height)=>{const color=chartColors(),plot={x:38,y:12,w:width-72,h:height-42},maxValue=Math.max(...reportTrend.map(item=>item.orderCount))*1.15;context.font='9px system-ui';context.fillStyle=color.text;context.textAlign='right';for(let index=0;index<5;index+=1){const y=plot.y+plot.h/4*index;context.strokeStyle=color.grid;context.beginPath();context.moveTo(plot.x,y);context.lineTo(plot.x+plot.w,y);context.stroke();context.fillText(`${Math.round(maxValue*(4-index)/4)}`,plot.x-7,y+3)}const closed=[],cancelled=[],complaints=[],hit=[];reportTrend.forEach((item,index)=>{const step=plot.w/reportTrend.length,x=plot.x+index*step+step*.5,barH=item.orderCount/maxValue*plot.h;context.fillStyle=color.primarySoft;context.fillRect(x-step*.28,plot.y+plot.h-barH,step*.56,barH);closed.push({x,y:plot.y+plot.h-item.closedCount/maxValue*plot.h});cancelled.push({x,y:plot.y+plot.h-item.cancelledCount/maxValue*plot.h});complaints.push({x,y:plot.y+plot.h-item.complaintOrderCount/maxValue*plot.h});hit.push({x,item});if(index%5===0||index===reportTrend.length-1){context.fillStyle=color.text;context.textAlign='center';context.fillText(item.date,x,height-8)}});drawLine(context,closed,color.teal,2);drawLine(context,cancelled,color.amber,1.5);drawLine(context,complaints,color.danger,1.5);canvas._chartPoints=hit})}
function bindCanvasTooltip(canvasId,tooltipId,formatter){const canvas=$(canvasId),tooltip=$(tooltipId);canvas.addEventListener('pointermove',event=>{const points=canvas._chartPoints||[];if(!points.length)return;const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,point=points.reduce((best,item)=>Math.abs(item.x-x)<Math.abs(best.x-x)?item:best,points[0]);tooltip.innerHTML=formatter(point.item);tooltip.style.left=`${clamp(point.x,70,rect.width-70)}px`;tooltip.style.top='18px';tooltip.hidden=false});canvas.addEventListener('pointerleave',()=>tooltip.hidden=true)}

function currentQualityRows(type=$('qualityType')?.value||'region'){const term=$('qualityKeyword')?.value.trim().toLowerCase()||'';return qualityRows(type).filter(item=>!term||item.name.toLowerCase().includes(term)||item.code.toLowerCase().includes(term))}
function updateQualitySummary(){const s=qualitySummary;$('qualityVolume').innerHTML=`${fmt(s.serviceCount)}<small> 单</small>`;$('qualityTimely').textContent=pct(rate(s.onTimeCount,s.serviceCount));$('qualityTimelyFraction').textContent=`${fmt(s.onTimeCount)} / ${fmt(s.serviceCount)} 单`;$('qualityFirstFix').textContent=pct(rate(s.firstTimeResolvedCount,s.serviceCount));$('qualityFirstFixFraction').textContent=`${fmt(s.firstTimeResolvedCount)} / ${fmt(s.serviceCount)} 单`;$('qualityRatingCoverage').textContent=pct(rate(s.ratedCount,s.serviceCount));$('qualityRatedFraction').textContent=`${fmt(s.ratedCount)} / ${fmt(s.serviceCount)} 单`;$('qualityRating').innerHTML=`${average(s.ratingTotal,s.ratedCount).toFixed(2)}<small> 分</small>`;$('qualityComplaintRate').textContent=pct(rate(s.complaintCount,s.serviceCount));$('qualityComplaintFraction').textContent=`${fmt(s.complaintCount)} / ${fmt(s.serviceCount)} 单`}
function qualityMetricValue(row,metric){return metric==='serviceCount'?row.serviceCount:row[metric]}
function qualityMetricText(row,metric){return metric==='serviceCount'?fmt(row.serviceCount):pct(row[metric])}
function renderQualityRanking(){const rows=currentQualityRows(),metric=qualityRankMetric,reverse=metric==='complaintRate',sorted=[...rows].sort((a,b)=>reverse?b[metric]-a[metric]:b[metric]-a[metric]),values=sorted.map(row=>qualityMetricValue(row,metric)),max=Math.max(...values,1),min=Math.min(...values,0),typeLabels={region:'区域',station:'服务站',personnel:'服务人员'};$('qualityComparisonType').textContent=typeLabels[$('qualityType').value];$('qualityRanking').innerHTML=sorted.map((row,index)=>{const value=qualityMetricValue(row,metric),width=metric==='serviceCount'?value/max*100:(value-min)/(max-min||1)*58+38,low=!reverse&&index>=Math.ceil(sorted.length*.7);return `<div class="ranking-row${low?' is-relative-low':''}"><strong title="${row.name}">${row.name}</strong><span class="ranking-track"><i class="ranking-fill" style="width:${width.toFixed(1)}%"></i></span><span class="ranking-value">${qualityMetricText(row,metric)}</span><span class="ranking-count">${fmt(row.serviceCount)} 单</span></div>`}).join('')||'<div class="empty-inline">没有匹配对象</div>'}
function attentionScore(row){return row.serviceCount*(100-row.timely)+row.complaintCount*220+(100-row.firstFix)*90}
function renderQualityAttention(){const rows=qualityRows(attentionType).sort((a,b)=>attentionScore(b)-attentionScore(a)).slice(0,5);$('qualityAttention').innerHTML=rows.map((row,index)=>`<div class="attention-row" data-quality-source="${attentionType}" data-quality-id="${row.id}"><span class="attention-rank">${String(index+1).padStart(2,'0')}</span><span class="attention-copy"><strong>${row.name}</strong><small>${row.code} · 服务量 ${fmt(row.serviceCount)} 单</small></span><span class="attention-signal"><strong>${pct(row.timely)}</strong><small>及时率 · 投诉 ${row.complaintCount}</small></span><span class="icon">${svgIcon('chevron-right')}</span></div>`).join('')}
function renderQualityTable(){const rows=currentQualityRows(),labels={region:'区域',station:'服务站',personnel:'服务人员'},type=$('qualityType').value;$('qualityTableType').textContent=labels[type];$('qualityRows').innerHTML=rows.map(row=>`<tr data-quality-source="${type}" data-quality-id="${row.id}"><td><span class="object-cell"><strong>${row.name}</strong><small>${row.code}</small></span></td><td class="number-cell">${fmt(row.serviceCount)}</td><td class="number-cell">${pct(row.timely)}</td><td class="number-cell">${pct(row.firstFix)}</td><td class="number-cell">${row.rating.toFixed(2)}</td><td class="number-cell${row.complaintCount>=10?' is-danger':''}">${row.complaintCount}</td><td><button class="v2-row-action" type="button" aria-label="查看 ${row.name}"><span class="icon">${svgIcon('chevron-right')}</span></button></td></tr>`).join('');$('qualityTableCount').textContent=`共 ${rows.length} 条${labels[type]}汇总事实`;bindQualityDetails()}
function findQuality(source,id){return qualityRows(source).find(row=>row.id===id)}
function showQualityDetail(source,id){const row=findQuality(source,id);if(!row)return;openDrawer(row.name,detailHtml([['对象',row.name],['服务量',`${fmt(row.serviceCount)} 单`],['及时完成',`${fmt(row.onTimeCount)} / ${fmt(row.serviceCount)} 单`],['一次完工',`${fmt(row.firstTimeResolvedCount)} / ${fmt(row.serviceCount)} 单`],['已有评价',`${fmt(row.ratedCount)} 单`],['评价均分',row.rating.toFixed(2)],['投诉',`${row.complaintCount} 单`]],'下钻继承统计对象、当前周期和授权组织范围；百分比由该对象对应分子与分母计算。'),`服务质量：${source}=${row.code}`)}
function bindQualityDetails(){document.querySelectorAll('[data-quality-source]').forEach(row=>row.addEventListener('click',()=>showQualityDetail(row.dataset.qualitySource,row.dataset.qualityId)))}
function renderQuality(){updateQualitySummary();renderQualityRanking();renderQualityAttention();renderQualityTable();drawQualityTrend();$('qualityTrendScope').textContent=`${$('qualityStart').value.replaceAll('-','/')}—${$('qualityEnd').value.replaceAll('-','/')} · 全国汇总`}

function reportRows(){return reportGroups[reportDimension].map((item,index)=>({id:`${reportDimension}-${index}`,name:item[0],orderCount:item[1],closedCount:item[2],cancelledCount:item[3],complaintOrderCount:item[4]}))}
function updateReportSummary(){const s=reportSummary;$('reportTotal').textContent=fmt(s.orderCount);$('reportClosed').textContent=fmt(s.closedCount);$('reportCancelled').textContent=fmt(s.cancelledCount);$('reportComplaints').textContent=fmt(s.complaintOrderCount);$('reportClosedRate').textContent=pct(rate(s.closedCount,s.orderCount));$('reportCancelledRate').textContent=pct(rate(s.cancelledCount,s.orderCount));$('reportComplaintRate').textContent=pct(rate(s.complaintOrderCount,s.orderCount))}
function renderReportStructure(){const rows=reportRows().slice(0,6),max=Math.max(...rows.map(row=>row.orderCount),1);$('reportStructureType').textContent=reportLabels[reportDimension];$('reportStructure').innerHTML=rows.map(row=>`<div class="structure-row"><strong title="${row.name}">${row.name}</strong><span class="structure-track"><i style="width:${row.orderCount/max*100}%"></i></span><span class="structure-total">${fmt(row.orderCount)}</span><span class="structure-marker"><i></i>${row.closedCount}</span><span class="structure-marker is-cancelled"><i></i>${row.cancelledCount}</span><span class="structure-marker is-complaint"><i></i>${row.complaintOrderCount}</span></div>`).join('');$('reportStructureNote').textContent=reportDimension==='product'?'商品组内按工单 ID 去重；商品组之间禁止加总。':'各组同组内按工单 ID 去重。'}
function renderReportObservations(){const s=reportSummary,top=reportRows()[0];const items=[['工单量较上期上升',`本期 ${fmt(s.orderCount)} 单，较上期 3,317 单增加 12.6%。`],['关闭量保持增长',`当前已关闭 ${fmt(s.closedCount)} 单，占工单总数 ${pct(rate(s.closedCount,s.orderCount))}。`],['取消量有所下降',`当前已取消 ${fmt(s.cancelledCount)} 单，取消率 ${pct(rate(s.cancelledCount,s.orderCount))}。`],[`${reportLabels[reportDimension]}首位为 ${top.name}`,`${fmt(top.orderCount)} 单，占当前总量 ${pct(rate(top.orderCount,s.orderCount))}。`]];$('reportObservations').innerHTML=items.map((item,index)=>`<div class="observation-item"><strong>${index+1}. ${item[0]}</strong><p>${item[1]}</p></div>`).join('')}
function renderReportTable(){const rows=reportRows(),label=reportLabels[reportDimension];$('reportTableType').textContent=label;$('reportGroupHeader').textContent=label;$('reportTableDescription').textContent=reportDimension==='product'?'同组内按工单 ID 去重；跨商品组不可相加':'同组内按工单 ID 去重';$('reportRows').innerHTML=rows.map(row=>`<tr data-report-id="${row.id}"><td><span class="object-cell"><strong>${row.name}</strong><small>${label}分组</small></span></td><td class="number-cell">${fmt(row.orderCount)}</td><td class="number-cell">${fmt(row.closedCount)}</td><td class="number-cell">${fmt(row.cancelledCount)}</td><td class="number-cell">${fmt(row.complaintOrderCount)}</td><td class="number-cell">${pct(rate(row.closedCount,row.orderCount))}</td><td class="number-cell">${pct(rate(row.cancelledCount,row.orderCount))}</td><td class="number-cell">${pct(rate(row.complaintOrderCount,row.orderCount))}</td><td><button class="v2-row-action" type="button" aria-label="查看 ${row.name}"><span class="icon">${svgIcon('chevron-right')}</span></button></td></tr>`).join('');$('reportTableCount').textContent=`共 ${rows.length} 个${label}分组`;document.querySelectorAll('[data-report-id]').forEach(row=>row.addEventListener('click',()=>showReportDetail(row.dataset.reportId)))}
function showReportDetail(id){const row=reportRows().find(item=>item.id===id);if(!row)return;const label=reportLabels[reportDimension];openDrawer(row.name,detailHtml([['分组',row.name],['工单总数',`${fmt(row.orderCount)} 单`],['当前已关闭',`${fmt(row.closedCount)} 单`],['当前已取消',`${fmt(row.cancelledCount)} 单`],['有投诉工单',`${fmt(row.complaintOrderCount)} 单`],['工单数占比',pct(rate(row.orderCount,reportSummary.orderCount))]],`下钻继承创建日期、服务类型、建单来源、${label}分组键和授权范围；投诉与其他状态可能重叠。`),`运营报表：${label}=${row.name}`)}
function renderReport(){updateReportSummary();renderReportStructure();renderReportObservations();renderReportTable();drawReportTrend();$('reportTrendScope').textContent=`${$('reportStart').value.replaceAll('-','/')}—${$('reportEnd').value.replaceAll('-','/')} · 按创建日期`}

function validateRange(startId,endId,validationId,maxDays=93){const start=new Date($(startId).value),end=new Date($(endId).value),days=(end-start)/86400000+1;if(!Number.isFinite(days)||days<1){setValidation(validationId,'结束日期不能早于开始日期。');return false}if(days>maxDays){setValidation(validationId,`日期范围不能超过 ${maxDays} 天。`);return false}setValidation(validationId,'');return true}
function bindCommon(){document.querySelectorAll('.menu-group-title').forEach(button=>button.addEventListener('click',()=>{const group=button.closest('.menu-group');group.classList.toggle('is-open');button.setAttribute('aria-expanded',String(group.classList.contains('is-open')))}));document.querySelectorAll('[data-preview-link]').forEach(button=>button.addEventListener('click',()=>showToast(`${button.dataset.previewLink}：入口已保留`)));$('sidebarButton').addEventListener('click',()=>{const shell=$('appShell');shell.classList.toggle('is-sidebar-collapsed');$('sidebarButton').querySelector('span:last-child').textContent=shell.classList.contains('is-sidebar-collapsed')?'展开菜单':'收起菜单'});$('themeButton').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('themeButton').innerHTML=`<span class="icon">${svgIcon(dark?'sun':'moon')}</span>`;setTimeout(()=>page==='quality'?drawQualityTrend():drawReportTrend(),0)});$('refreshButton').addEventListener('click',()=>{pulse();setUpdated();page==='quality'?renderQuality():renderReport();showToast('演示数据已刷新')});$('fullscreenButton').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(_){showToast('浏览器未允许进入全屏')}});$('searchButton').addEventListener('click',()=>showToast('可从侧栏进入总部运营功能'));$('perspectiveButton').addEventListener('click',()=>showToast('当前工作视角：总部运营'));$('closeDrawer').addEventListener('click',closeDrawer);$('drawerCloseButton').addEventListener('click',closeDrawer);$('scrim').addEventListener('click',closeDrawer);$('drawerAction').addEventListener('click',()=>{closeDrawer();showToast(`已生成下钻条件：${drawerContext}`)});window.addEventListener('resize',()=>{clearTimeout(window.__chartResize);window.__chartResize=setTimeout(()=>page==='quality'?drawQualityTrend():drawReportTrend(),120)});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawer()});const today=new Date();$('fullDate').textContent=`${today.getFullYear()} 年 ${today.getMonth()+1} 月 ${today.getDate()} 日`}

function initQuality(){bindCanvasTooltip('qualityTrendCanvas','qualityChartTooltip',item=>`<strong>${item.date}</strong><br>服务量 ${fmt(item.serviceCount)} 单<br>及时率 ${pct(item.timely)}<br>一次完工率 ${pct(item.firstFix)}`);document.querySelectorAll('[data-quality-rank]').forEach(button=>button.addEventListener('click',()=>{qualityRankMetric=button.dataset.qualityRank;document.querySelectorAll('[data-quality-rank]').forEach(item=>item.classList.toggle('is-active',item===button));renderQualityRanking()}));document.querySelectorAll('[data-attention-type]').forEach(button=>button.addEventListener('click',()=>{attentionType=button.dataset.attentionType;document.querySelectorAll('[data-attention-type]').forEach(item=>item.classList.toggle('is-active',item===button));renderQualityAttention();bindQualityDetails()}));$('qualityQuery').addEventListener('click',()=>{if(!validateRange('qualityStart','qualityEnd','qualityValidation'))return;pulse();renderQuality();showToast('服务质量已按当前条件更新')});$('qualityReset').addEventListener('click',()=>{$('qualityStart').value='2026-08-22';$('qualityEnd').value='2026-09-21';$('qualityType').value='region';$('qualityKeyword').value='';setValidation('qualityValidation','');renderQuality();showToast('筛选条件已重置')});$('qualityType').addEventListener('change',()=>{renderQualityRanking();renderQualityTable()});$('qualityKeyword').addEventListener('keydown',event=>{if(event.key==='Enter')$('qualityQuery').click()});$('qualityExport').addEventListener('click',()=>showToast('导出任务已按当前条件提交，完成后进入下载中心获取'));renderQuality()}
function initReport(){bindCanvasTooltip('reportTrendCanvas','reportChartTooltip',item=>`<strong>${item.date}</strong><br>工单总数 ${fmt(item.orderCount)}<br>当前已关闭 ${fmt(item.closedCount)}<br>当前已取消 ${fmt(item.cancelledCount)}<br>有投诉工单 ${fmt(item.complaintOrderCount)}`);document.querySelectorAll('[data-report-dimension]').forEach(button=>button.addEventListener('click',()=>{reportDimension=button.dataset.reportDimension;document.querySelectorAll('[data-report-dimension]').forEach(item=>item.classList.toggle('is-active',item===button));renderReport();showToast(`已切换为按${reportLabels[reportDimension]}分析`)}));$('reportQuery').addEventListener('click',()=>{if(!validateRange('reportStart','reportEnd','reportValidation'))return;pulse();renderReport();showToast('运营报表已按当前条件更新')});$('reportReset').addEventListener('click',()=>{$('reportStart').value='2026-08-22';$('reportEnd').value='2026-09-21';$('reportServiceType').value='all';$('reportSource').value='all';setValidation('reportValidation','');renderReport();showToast('筛选条件已重置')});$('reportExport').addEventListener('click',()=>showToast('导出任务已按当前条件提交，完成后进入下载中心获取'));$('reportStateButton').addEventListener('click',()=>{const states=[['data',''],['loading','正在加载当前分组…'],['empty','当前筛选条件下暂无统计数据'],['error','统计加载失败，请重试'],['forbidden','当前账号没有运营报表访问权限']],state=states[reportStateIndex%states.length];reportStateIndex+=1;$('reportTableState').hidden=state[0]==='data';$('reportTableState').textContent=state[1];$('reportRows').closest('table').style.visibility=state[0]==='data'?'visible':'hidden';showToast(`状态演示：${state[0]}`)});renderReport()}

bindCommon();if(page==='quality')initQuality();else initReport()
})()
