const fs=require('node:fs')
const path=require('node:path')
const test=require('node:test')
const assert=require('node:assert/strict')
const root=path.resolve(__dirname,'..')
const quality=fs.readFileSync(path.join(root,'service-quality.html'),'utf8')
const report=fs.readFileSync(path.join(root,'operations-report.html'),'utf8')
const index=fs.readFileSync(path.join(root,'index.html'),'utf8')
const css=fs.readFileSync(path.join(root,'analytics.css'),'utf8')
const js=fs.readFileSync(path.join(root,'analytics.js'),'utf8')
const design=fs.readFileSync(path.join(root,'01-四视角后台原型设计说明.md'),'utf8')

test('总部运营工作台可进入两个专业分析页',()=>{assert.match(index,/运营工作台/);assert.match(index,/href="service-quality\.html"/);assert.match(index,/href="operations-report\.html"/)})
test('服务质量第一版只读并覆盖五项事实',()=>{for(const copy of ['服务量','及时率','一次完工率','评价均分','投诉数','不允许人工录入'])assert.match(quality,new RegExp(copy));assert.match(quality,/不对多个对象的百分比再求平均/)})
test('运营报表覆盖七个白名单维度和基础指标',()=>{for(const dimension of ['日期','服务类型','建单来源','区域','服务站','门店','商品'])assert.match(report,new RegExp(`data-dimension="[^"]+">${dimension}`));for(const copy of ['工单数','当前已关闭','当前已取消','有投诉工单','最多 93 天'])assert.match(report,new RegExp(copy))})
test('商品去重和当前状态口径已明示',()=>{assert.match(report,/商品维度不可跨组相加/);assert.match(report,/关闭与取消为查询时的当前状态/);assert.match(js,/多个投诉不重复累计/)})
test('两页具备查询、重置、切维、下钻和四种状态',()=>{for(const token of ['renderQuality','selectQuality','showQualityDetail','renderReport','showReportDetail','runReportQuery','setTableState'])assert.ok(js.includes(token),`missing ${token}`);for(const state of ['data','loading','empty','error']){assert.match(quality,new RegExp(`data-table-state="${state}"`));assert.match(report,new RegExp(`data-table-state="${state}"`))}})
test('原型诚实标识数据和未完成边界',()=>{assert.match(quality,/原型演示数据/);assert.match(report,/原型演示数据/);assert.doesNotMatch(quality,/已验收/);assert.doesNotMatch(report,/已验收/);assert.match(report,/尚未完成/);assert.match(design,/服务质量/)} )
test('新页动效可按系统偏好降级',()=>{assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(js,/prefers-reduced-motion: reduce/)})
