'use strict';
const {readFileSync}=require('node:fs');const {resolve}=require('node:path');const vm=require('node:vm');const test=require('node:test');const assert=require('node:assert/strict');
const CHEN='WX202609130018',LIN='AZ202609130021',ZHAO='AZ202609110006',LIU='WX202609140031',WU='AZ202609140032';
function fixture(pastAppointment=false){const window={};for(const f of ['worker.js','worker-schedule.js','worker-map.js'])vm.runInNewContext(readFileSync(resolve(__dirname,'../'+f),'utf8').replace("queue:'pending',flag:'审核退回'",pastAppointment?"queue:'pending',flag:'已预约'":"queue:'pending',flag:'审核退回'"),{window});return {w:window.TOTO_WORKER,s:window.TOTO_WORKER_SCHEDULE,m:window.TOTO_WORKER_MAP};}
const ids=rows=>Array.from(rows,r=>r.task.id);
test('schedule shares authorized tasks but does not hide other dates behind the list filter',()=>{const {w,s}=fixture();w.actAction('queue','returned');assert.equal(w.filteredTasks().length,1);assert.deepEqual(ids(s.entries()),[CHEN,LIN]);assert.deepEqual(ids(s.entries('2026-09-14')),[LIU,WU]);assert.equal(s.unplanned().length,3);assert.equal(s.entries('2026-09-20').length,0);});
test('week and month navigation handles week/year boundaries and leap days without timezone drift',()=>{const {s}=fixture();s.setDate('2026-09-13');assert.deepEqual(Array.from(s.week()),['2026-09-07','2026-09-08','2026-09-09','2026-09-10','2026-09-11','2026-09-12','2026-09-13']);s.act('week','1');assert.equal(s.snapshot().date,'2026-09-20');s.setDate('2026-12-31');s.act('week','1');assert.equal(s.snapshot().date,'2027-01-07');s.act('month');s.act('month-step','-1');assert.equal(s.snapshot().month,'2026-12');assert.ok(s.validDate('2028-02-29'));assert.throws(()=>s.setDate('2026-02-29'),/有效日期/);s.act('today');assert.equal(s.snapshot().date,'2026-09-13');});
test('overlap requires intersecting confirmed time windows; adjacent and cancelled slots are not conflicts',()=>{const {s}=fixture();const future=s.entries('2026-09-14');assert.equal(s.conflicts(future).size,2);assert.equal(s.conflicts(s.entries()).size,0);const a={kind:'current',key:'a',start:'09:00',end:'10:00',task:{queue:'pending',flag:'已预约'}},b={...a,key:'b',start:'10:00',end:'11:00'};assert.equal(s.conflicts([a,b]).size,0);b.start='09:30';assert.equal(s.conflicts([a,b]).size,2);b.task={queue:'cancelled',flag:'已取消'};assert.equal(s.conflicts([a,b]).size,0);});
test('past labels distinguish completion, closure, returned materials and follow-up without automatic overdue',()=>{const {s}=fixture();assert.equal(s.status(s.entries('2026-09-12')[0]).label,'已完工 · 审核中');assert.equal(s.status(s.entries('2026-09-11')[0]).label,'退回待补');assert.equal(s.status(s.entries('2026-09-09')[0]).label,'已取消');const r={kind:'current',date:'2026-09-12',task:{queue:'pending',flag:'已预约'}};assert.equal(s.status(r).label,'预约已过 · 需跟进');r.task.queue='closed';assert.equal(s.status(r).label,'已关闭');assert.equal(s.followup(r),false);s.setDate('2026-09-12');assert.match(s.render(),/展开已处理与变更记录/);s.act('archive');assert.match(s.render(),/已完工 · 审核中/);});
test('confirmed rescheduling retains the original past appointment and updates future calendar and map together',()=>{const {w,s,m}=fixture(true);w.actAction('task',ZHAO);w.submitAction('appointment',{result:'confirmed',date:'2026-09-15',start:'09:00',end:'10:00',note:'客户确认改约'});assert.equal(s.entries('2026-09-11')[0].kind,'history');assert.equal(s.entries('2026-09-11')[0].outcome,'已改约');assert.equal(s.entries('2026-09-15')[0].kind,'current');m.openDate('2026-09-15');assert.equal(m.rows()[0].id,ZHAO);w.submitAction('appointment',{result:'confirmed',date:'2026-09-15',start:'09:00',end:'10:00',note:'再次确认同一时间'});assert.equal(s.entries('2026-09-11').length,1);});
test('unconfirmed contact attempts never occupy future dates; invalid submissions do not archive original slots',()=>{const {w,s}=fixture();w.actAction('task',LIU);assert.throws(()=>w.submitAction('appointment',{result:'confirmed',date:'2026-09-15',start:'12:00',end:'10:00',note:'错误时间'}),/结束时间/);assert.equal(s.entries('2026-09-14').length,2);w.submitAction('appointment',{result:'later',date:'2026-09-15',start:'09:00',end:'11:00',note:'待回复'});assert.equal(s.entries('2026-09-14').length,1);assert.equal(s.entries('2026-09-15').length,0);assert.ok(s.unplanned().some(t=>t.id===LIU));});
test('exception clears future schedule, preserves historical appointment and keeps recovery pending',()=>{const {w,s}=fixture(true);w.actAction('task',ZHAO);w.submitAction('exception',{flag:'已取消',reason:'客户取消'});const old=s.entries('2026-09-11')[0];assert.equal(old.kind,'history');assert.equal(old.outcome,'已取消');w.submitAction('restore',{reason:'客户要求恢复',confirmed:true});assert.equal(s.entries('2026-09-11').length,1);assert.ok(!s.unplanned().some(t=>t.id===ZHAO));});
test('selected-day map uses that date and drops tasks that no longer belong to it',()=>{const {w,s,m}=fixture();s.setDate('2026-09-14');assert.equal(s.act('date-map'),'w-map');assert.deepEqual(Array.from(m.rows(),t=>t.id),[LIU,WU]);assert.doesNotMatch(s.render(),/安排当日路线|data-wsched="date-route"/);w.actAction('task',LIU);w.submitAction('appointment',{result:'later',note:'等待回复'});m.render();assert.deepEqual(Array.from(m.rows(),t=>t.id),[WU]);assert.throws(()=>m.openDate('2026-02-30'),/有效日期/);});
test('remote appointments appear in the selected-day map list but never receive a marker',()=>{const {w,s,m}=fixture();s.act('appointment','ZD202609130008');assert.equal(w.snapshot().taskId,'ZD202609130008');w.submitAction('appointment',{result:'confirmed',date:'2026-09-14',start:'13:00',end:'14:00',note:'已确认电话指导'});assert.equal(s.entries('2026-09-14').length,3);m.openDate('2026-09-14');assert.equal(m.rows().length,3);assert.equal(m.groups().length,2);assert.equal(m.point(m.rows().find(t=>t.type==='远程指导')),null);});
test('calendar context survives detail/return while company switch and logout reset dates and map records',()=>{const {w,s,m}=fixture();s.setDate('2026-09-14');s.act('detail',LIU);w.onNavigate('w-detail');w.onNavigate('w-schedule');assert.equal(s.snapshot().date,'2026-09-14');assert.equal(s.snapshot().view,'day');w.submitAction('company',{company:'苏州示例服务企业',confirmed:true});assert.equal(s.snapshot().date,'2026-09-13');assert.equal(s.entries().length,0);assert.equal(s.unplanned().length,0);m.openDate('2026-09-14');assert.equal(m.rows().length,0);w.actAction('logout');assert.equal(s.entries('2026-09-14').length,0);});

test('detail navigation opens only the selected task on the native-capability map',()=>{
  const {w,m}=fixture();w.actAction('task',LIN);assert.equal(w.actAction('location'),'w-map');assert.equal(m.snapshot().view,'map');assert.deepEqual(Array.from(m.rows(),t=>t.id),[LIN]);assert.match(m.render(),/打开微信位置页/);
  w.actAction('task','WX202609120007');w.actAction('location');assert.equal(m.snapshot().view,'map');assert.match(m.render(),/核实地址/);
});
