-- 已于 2026-09-12 经用户授权执行并验证。重新使用前须重新预检；仅追加缺失读取 API，不改角色/操作授权。
-- 目标库必须为 gaia_wh_init_wzy。02-create-complaint-tables.sql 成功后才能执行。
START TRANSACTION;
SELECT id,code,api_list FROM sys_module WHERE code IN ('afsReport','afsComplaint') FOR UPDATE;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/reports/permissions'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000059 AND code='afsReport' AND path='afterSales/dataCenter/report' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/reports/permissions',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/reports/work-orders'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000059 AND code='afsReport' AND path='afterSales/dataCenter/report' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/reports/work-orders',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/complaints'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000022 AND code='afsComplaint' AND path='afterSales/customerService/complaint' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/complaints',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/complaints/permissions'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000022 AND code='afsComplaint' AND path='afterSales/customerService/complaint' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/complaints/permissions',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/complaints/*'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000022 AND code='afsComplaint' AND path='afterSales/customerService/complaint' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/complaints/*',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
UPDATE sys_module SET api_list=CONCAT_WS(',',NULLIF(api_list,''),'GET$/api/afterSales/complaints/*/history'),update_user=-1,update_time=CURRENT_TIMESTAMP WHERE id=2026090800000022 AND code='afsComplaint' AND path='afterSales/customerService/complaint' AND enable=1 AND COALESCE(FIND_IN_SET('GET$/api/afterSales/complaints/*/history',REGEXP_REPLACE(api_list,'[[:space:]]','')),0)=0;
SELECT id,code,api_list FROM sys_module WHERE code IN ('afsReport','afsComplaint') ORDER BY code;
COMMIT;
